apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"catest-gateway","namespace":"catest"},"spec":{"ports":[{"name":"http","port":33080,"targetPort":33080}],"selector":{"app":"catest-gateway"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-03-15T19:39:23Z"
  name: catest-gateway
  namespace: catest
  resourceVersion: "1797791"
  uid: c308c9cd-e1db-4427-bd82-dedc374dce7f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.56.219
  clusterIPs:
  - 10.102.56.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30924
    port: 33080
    protocol: TCP
    targetPort: 33080
  selector:
    app: catest-gateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
