apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"catest-web-base","namespace":"catest"},"spec":{"ports":[{"name":"http","port":33000,"targetPort":3000}],"selector":{"app":"catest-web"},"type":"LoadBalancer"}}
  creationTimestamp: "2026-03-16T11:57:46Z"
  name: catest-web-base
  namespace: catest
  resourceVersion: "1932009"
  uid: 9d2445fa-0959-4fc0-90e4-3f2361061649
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.105.160.110
  clusterIPs:
  - 10.105.160.110
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31986
    port: 33000
    protocol: TCP
    targetPort: 3000
  selector:
    app: catest-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
