apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 34321
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-ext
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 36333
      targetPort: 6333
      name: http
    - port: 36334
      targetPort: 6334
      name: grpc
  selector:
    app: qdrant
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-ext
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 37474
      targetPort: 7474
      name: http
    - port: 37687
      targetPort: 7687
      name: bolt
  selector:
    app: neo4j
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ext
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 39092
      targetPort: 39092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: arroyo-ext
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 35115
      targetPort: 5115
  selector:
    app: arroyo
