"use client";

import React, { useState, useCallback } from "react";
import { type PluginGroup } from "@catest/ui/plugins";
import { Card, Badge, Button, VictorianDivider, cn } from "@catest/ui";
import {
  Download,
  FileOutput,
  Eye,
  CheckCircle2,
  Copy,
  Check,
  FileText,
  ArrowLeftRight,
  Settings2,
  Loader2,
} from "lucide-react";

// ── Segment data type (mirrors the review editor) ────────────────────
interface Segment {
  id: number;
  source: string;
  target: string;
  remark: string;
  status: "verified" | "review" | "draft";
  match: string;
}

// ── Mock: in production this would come from shared state / API ──────
const REVIEW_SEGMENTS: Segment[] = [
  {
    id: 1,
    source: "export async function handleRequest(req: Request) {",
    target: "export async function handleRequest(req: Request) {",
    remark: "Entry point verified against Security Policy v2.1.",
    status: "verified",
    match: "100% MB",
  },
  {
    id: 2,
    source: "  const session = await getSession(req);",
    target: "  const auth = await validateAuthorization(req);",
    remark:
      "Non-compliant with 'Auth-Standard-2026'. Termbase suggests using centralized validator.",
    status: "review",
    match: "92% TB",
  },
  {
    id: 3,
    source:
      "  if (!auth.isValid) return new Response('Unauthorized', { status: 401 });",
    target:
      "  if (!auth.isValid) return new Response('Unauthorized', { status: 401 });",
    remark: "Standard error guard. Complies with Global Exception Pattern.",
    status: "verified",
    match: "100% MB",
  },
  {
    id: 4,
    source: "  return processTask(auth.user);",
    target: "  return processSyncTask(auth.user, req.signal);",
    remark:
      "Proposed change: Add cancellation signal for better resource lifecycle management.",
    status: "draft",
    match: "Fuzzy",
  },
  {
    id: 5,
    source: "}",
    target: "}",
    remark: "",
    status: "verified",
    match: "Static",
  },
];

// ── .catest file format serializer ───────────────────────────────────
type ExportFormat = "catest" | "tsv" | "xliff";

function serializeCatest(segments: Segment[], projectName: string): string {
  const header = [
    `# ═══════════════════════════════════════════════════════════`,
    `# CATEST Review Export`,
    `# Project:  ${projectName}`,
    `# Date:     ${new Date().toISOString()}`,
    `# Segments: ${segments.length}`,
    `# Format:   .catest v1.0 — Bilingual Alignment`,
    `# ═══════════════════════════════════════════════════════════`,
    ``,
  ].join("\n");

  const body = segments
    .map((seg) => {
      const statusTag =
        seg.status === "verified"
          ? "[✓ VERIFIED]"
          : seg.status === "review"
            ? "[⚠ REVIEW]"
            : "[◇ DRAFT]";
      const matchTag = seg.match ? `  (${seg.match})` : "";

      return [
        `┌─── Segment ${String(seg.id).padStart(3, "0")} ${statusTag}${matchTag}`,
        `│ SRC │ ${seg.source}`,
        `│ TGT │ ${seg.target}`,
        ...(seg.remark
          ? [`│ REM │ ${seg.remark}`]
          : []),
        `└${"─".repeat(60)}`,
      ].join("\n");
    })
    .join("\n\n");

  const footer = [
    ``,
    `# ─── Summary ──────────────────────────────────────────────`,
    `# Verified: ${segments.filter((s) => s.status === "verified").length}`,
    `# Review:   ${segments.filter((s) => s.status === "review").length}`,
    `# Draft:    ${segments.filter((s) => s.status === "draft").length}`,
    `# ═══════════════════════════════════════════════════════════`,
    `# Generated by CATEST Review Engine`,
    `# https://catest.io`,
  ].join("\n");

  return header + body + "\n" + footer;
}

function serializeTsv(segments: Segment[]): string {
  const header = "ID\tStatus\tSource\tTarget\tMatch\tRemark";
  const rows = segments.map(
    (s) =>
      `${s.id}\t${s.status}\t${s.source}\t${s.target}\t${s.match}\t${s.remark}`
  );
  return [header, ...rows].join("\n");
}

function serializeXliff(segments: Segment[], projectName: string): string {
  const units = segments
    .map(
      (s) => `    <trans-unit id="${s.id}" state="${s.status}">
      <source>${escapeXml(s.source)}</source>
      <target>${escapeXml(s.target)}</target>
      ${s.remark ? `<note>${escapeXml(s.remark)}</note>` : ""}
    </trans-unit>`
    )
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file original="${projectName}" source-language="src" target-language="tgt" datatype="plaintext">
    <body>
${units}
    </body>
  </file>
</xliff>`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ── Preview Panel ────────────────────────────────────────────────────
function ExportPreviewPlugin() {
  const [format, setFormat] = useState<ExportFormat>("catest");
  const [showPreview, setShowPreview] = useState(false);
  const [copied, setCopied] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const projectName = "Auth-Logic-Review-2026";
  const segments = REVIEW_SEGMENTS;

  const getContent = useCallback(() => {
    switch (format) {
      case "catest":
        return serializeCatest(segments, projectName);
      case "tsv":
        return serializeTsv(segments);
      case "xliff":
        return serializeXliff(segments, projectName);
    }
  }, [format, segments, projectName]);

  const getExt = () =>
    format === "catest" ? ".catest" : format === "tsv" ? ".tsv" : ".xliff";
  const getMime = () =>
    format === "xliff" ? "application/xml" : "text/plain";

  const handleExport = useCallback(() => {
    setExporting(true);
    // Simulate brief processing
    setTimeout(() => {
      const content = getContent();
      const blob = new Blob([content], { type: `${getMime()};charset=utf-8` });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${projectName}${getExt()}`;
      a.click();
      URL.revokeObjectURL(url);
      setExporting(false);
      setExported(true);
      setTimeout(() => setExported(false), 3000);
    }, 400);
  }, [getContent, projectName, format]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(getContent());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [getContent]);

  const statusCounts = {
    verified: segments.filter((s) => s.status === "verified").length,
    review: segments.filter((s) => s.status === "review").length,
    draft: segments.filter((s) => s.status === "draft").length,
  };

  return (
    <div className="space-y-5">
      {/* Format selector + stats */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileOutput className="w-4 h-4 text-[var(--text-brass)]" />
          <span className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest">
            Export Format
          </span>
        </div>
        <div className="flex items-center gap-3 text-[9px] font-bold text-[var(--text-muted)]">
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#4a8b6e]" />
            {statusCounts.verified} Verified
          </span>
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#e67e22]" />
            {statusCounts.review} Review
          </span>
          <span className="flex items-center gap-1">
            <span className="w-1.5 h-1.5 rounded-full bg-[#3e1b0d]" />
            {statusCounts.draft} Draft
          </span>
        </div>
      </div>

      {/* Format tabs */}
      <div
        className="flex gap-1 p-1 rounded-sm border border-[#3e1b0d]/30"
        style={{
          background:
            "linear-gradient(180deg, rgba(26,17,8,0.6), rgba(13,10,4,0.4))",
        }}
      >
        {(
          [
            { id: "catest", label: ".catest", desc: "Bilingual Alignment" },
            { id: "tsv", label: ".tsv", desc: "Tab-Separated" },
            { id: "xliff", label: ".xliff", desc: "XLIFF 1.2" },
          ] as const
        ).map((f) => (
          <button
            key={f.id}
            onClick={() => setFormat(f.id)}
            className={cn(
              "flex-1 py-2.5 px-3 text-[10px] font-black uppercase tracking-wider transition-all rounded-sm",
              format === f.id
                ? "glass-card text-[#c9a84c] shadow-lg border border-[#b87333]/20"
                : "text-[var(--text-muted)] hover:text-[var(--text-secondary)]"
            )}
          >
            <div>{f.label}</div>
            <div className="text-[8px] font-medium tracking-normal normal-case opacity-60 mt-0.5">
              {f.desc}
            </div>
          </button>
        ))}
      </div>

      {/* Export info card */}
      <div
        className="p-4 rounded-sm border border-[#b87333]/15"
        style={{
          background:
            "linear-gradient(135deg, rgba(26,17,8,0.7), rgba(13,10,4,0.9))",
          boxShadow:
            "inset 0 1px 0 rgba(255,240,200,0.05), inset 0 -1px 2px rgba(0,0,0,0.4)",
        }}
      >
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <FileText className="w-3.5 h-3.5 text-[var(--text-brass)]" />
            <span className="text-xs font-bold text-[var(--text-primary)]">
              {projectName}
              {getExt()}
            </span>
          </div>
          <Badge className="bg-[#b87333]/10 text-[var(--text-muted)] border-[#b87333]/20 text-[9px] px-1.5 py-0">
            {segments.length} segments
          </Badge>
        </div>

        <div className="flex items-center gap-2 text-[9px] text-[var(--text-muted)] font-medium">
          <ArrowLeftRight className="w-3 h-3" />
          <span>
            Source ↔ Target bilingual comparison with status markers &amp;
            remarks
          </span>
        </div>
      </div>

      <VictorianDivider />

      {/* Action buttons */}
      <div className="flex gap-3">
        <Button
          variant="secondary"
          size="sm"
          className="flex-1"
          onClick={() => setShowPreview(!showPreview)}
        >
          <Eye className="w-3.5 h-3.5 mr-1.5" />
          {showPreview ? "Hide Preview" : "Preview"}
        </Button>
        <Button
          variant="secondary"
          size="sm"
          onClick={handleCopy}
        >
          {copied ? (
            <Check className="w-3.5 h-3.5 mr-1.5 text-[#4a8b6e]" />
          ) : (
            <Copy className="w-3.5 h-3.5 mr-1.5" />
          )}
          {copied ? "Copied" : "Copy"}
        </Button>
        <Button
          variant="copper"
          size="sm"
          className="flex-1"
          onClick={handleExport}
          disabled={exporting}
        >
          {exporting ? (
            <Loader2 className="w-3.5 h-3.5 mr-1.5 animate-spin" />
          ) : exported ? (
            <CheckCircle2 className="w-3.5 h-3.5 mr-1.5 text-[#4a8b6e]" />
          ) : (
            <Download className="w-3.5 h-3.5 mr-1.5" />
          )}
          {exporting
            ? "Exporting..."
            : exported
              ? "Exported!"
              : `Export ${getExt()}`}
        </Button>
      </div>

      {/* Preview panel */}
      {showPreview && (
        <div className="animate-in slide-in-from-top-2 duration-300">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[9px] font-black text-[var(--text-muted)] uppercase tracking-widest">
              File Preview
            </span>
            <span className="text-[9px] font-mono text-[var(--text-muted)]">
              {getContent().length} chars
            </span>
          </div>
          <div
            className="relative rounded-sm overflow-hidden border border-[#3e1b0d]/30"
            style={{
              background: "#0a0704",
              boxShadow:
                "inset 0 3px 10px rgba(0,0,0,0.7), inset 0 -1px 0 rgba(255,240,200,0.03)",
            }}
          >
            {/* Terminal scanline effect */}
            <div
              className="absolute inset-0 pointer-events-none opacity-[0.02]"
              style={{
                background:
                  "repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(255,255,255,0.1) 2px, rgba(255,255,255,0.1) 4px)",
              }}
            />
            <pre className="relative p-4 text-[10px] font-mono leading-relaxed text-[#e8d5b5] overflow-auto max-h-[400px] whitespace-pre steam-scroll">
              {getContent()}
            </pre>
          </div>
        </div>
      )}
    </div>
  );
}

// ── Options Plugin (filter what to export) ───────────────────────────
function ExportOptionsPlugin() {
  const [includeVerified, setIncludeVerified] = useState(true);
  const [includeReview, setIncludeReview] = useState(true);
  const [includeDraft, setIncludeDraft] = useState(true);
  const [includeRemarks, setIncludeRemarks] = useState(true);

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-1">
        <Settings2 className="w-3.5 h-3.5 text-[var(--text-brass)]" />
        <span className="text-[10px] font-black text-[var(--text-muted)] uppercase tracking-widest">
          Export Options
        </span>
      </div>

      <div className="space-y-2">
        {[
          {
            label: "Include Verified Segments",
            checked: includeVerified,
            set: setIncludeVerified,
            color: "#4a8b6e",
          },
          {
            label: "Include Review Segments",
            checked: includeReview,
            set: setIncludeReview,
            color: "#e67e22",
          },
          {
            label: "Include Draft Segments",
            checked: includeDraft,
            set: setIncludeDraft,
            color: "#3e1b0d",
          },
          {
            label: "Include Remarks / Notes",
            checked: includeRemarks,
            set: setIncludeRemarks,
            color: "#b87333",
          },
        ].map((opt, i) => (
          <label
            key={i}
            className="flex items-center gap-3 p-2.5 rounded-sm cursor-pointer hover:bg-[#b87333]/[0.04] transition-colors group"
          >
            <div className="relative">
              <input
                type="checkbox"
                checked={opt.checked}
                onChange={(e) => opt.set(e.target.checked)}
                className="sr-only peer"
              />
              <div
                className="w-4 h-4 rounded-sm border-2 transition-all peer-checked:border-[#c9a84c] peer-checked:bg-[#c9a84c]/20"
                style={{
                  borderColor: opt.checked
                    ? "#c9a84c"
                    : "rgba(62,27,13,0.5)",
                  background: opt.checked
                    ? "linear-gradient(135deg, rgba(201,168,76,0.2), rgba(184,115,51,0.1))"
                    : "rgba(0,0,0,0.3)",
                  boxShadow: opt.checked
                    ? "inset 0 1px 2px rgba(0,0,0,0.3), 0 0 4px rgba(201,168,76,0.2)"
                    : "inset 0 1px 3px rgba(0,0,0,0.5)",
                }}
              >
                {opt.checked && (
                  <Check className="w-3 h-3 text-[#c9a84c] absolute top-0 left-0" />
                )}
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span
                className="w-1.5 h-1.5 rounded-full"
                style={{ background: opt.color }}
              />
              <span className="text-[10px] font-bold text-[var(--text-secondary)] uppercase tracking-wider group-hover:text-[var(--text-primary)] transition-colors">
                {opt.label}
              </span>
            </div>
          </label>
        ))}
      </div>
    </div>
  );
}

// ── Plugin Group ─────────────────────────────────────────────────────
export const ExportPluginGroup: PluginGroup = {
  id: "review-export",
  name: "Export .catest",
  plugins: [
    {
      id: "export-preview",
      name: "Export & Preview",
      component: ExportPreviewPlugin as React.ComponentType<unknown>,
    },
    {
      id: "export-options",
      name: "Export Options",
      component: ExportOptionsPlugin as React.ComponentType<unknown>,
    },
  ],
};
