-- Arroyo SQL Pipeline: RAG Data Cleaning & Formatting
-- Subscribes to: catest.rag.ingest
-- Publishes to: catest.rag.cleaned

-- 1. Define the source Kafka topic generated by the Gateway
CREATE TABLE raw_rag_items (
    id TEXT,
    workspace_id TEXT,
    file_path TEXT,
    source_text TEXT,
    target_text TEXT,
    `timestamp` TIMESTAMP
) WITH (
    connector = 'kafka',
    bootstrap_servers = 'kafka:9092',
    topic = 'catest.rag.ingest',
    type = 'source',
    format = 'json'
);

-- 2. Define the destination Kafka topic that the Rust Consumer will read
CREATE TABLE cleaned_rag_items (
    id TEXT,
    workspace_id TEXT,
    file_path TEXT,
    cleaned_source TEXT,
    cleaned_target TEXT,
    word_count INT,
    `timestamp` TIMESTAMP
) WITH (
    connector = 'kafka',
    bootstrap_servers = 'kafka:9092',
    topic = 'catest.rag.cleaned',
    type = 'sink',
    format = 'json'
);

-- 3. Streaming Transformation Pipeline
-- Filters out very short or empty segments
-- Cleans whitespace and counts words
INSERT INTO cleaned_rag_items
SELECT 
    id,
    workspace_id,
    file_path,
    -- Basic cleaning: trim spaces
    TRIM(source_text) as cleaned_source,
    TRIM(target_text) as cleaned_target,
    -- Simple word count heuristic
    LENGTH(source_text) - LENGTH(REPLACE(source_text, ' ', '')) + 1 as word_count,
    `timestamp`
FROM raw_rag_items
WHERE 
    source_text IS NOT NULL 
    AND target_text IS NOT NULL
    AND LENGTH(TRIM(source_text)) > 5; -- Filter out trivial fragments
