apiVersion: apps/v1
kind: Deployment
metadata:
  name: catest-ai-consumer
  namespace: catest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catest-ai-consumer
  template:
    metadata:
      labels:
        app: catest-ai-consumer
    spec:
      serviceAccountName: catest-service-account
      containers:
        - name: ai-consumer
          image: ghcr.io/ulyssesleolee/catest-ai-consumer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CATEST_AI_SERVICE_NAME
              value: "ai-consumer"
            - name: CATEST_AI_KAFKA_BROKER
              value: "kafka:39092"
            - name: CATEST_AI_KAFKA_CONSUMER_GROUP
              value: "ai_rag_group"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
