apiVersion: apps/v1
kind: Deployment
metadata:
  name: catest-intelligence
  namespace: catest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catest-intelligence
  template:
    metadata:
      labels:
        app: catest-intelligence
    spec:
      containers:
        - name: embedding
          image: ghcr.io/ulyssesleolee/catest-embedding:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: "postgres://catest:password@postgres:34321/catest_intelligence"
            - name: QDRANT_URL
              value: "http://qdrant:36334"
            - name: QDRANT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: catest-app-secrets
                  key: QDRANT_API_KEY

            - name: MEMGRAPH_URI
              value: "bolt://memgraph:37687"
            - name: MEMGRAPH_USER
              value: ""
            - name: MEMGRAPH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: memgraph-secrets
                  key: memgraph-password
            - name: KAFKA_BROKER
              value: "kafka:39092"
