apiVersion: v1
kind: ServiceAccount
metadata:
  name: catest-service-account
  namespace: catest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: catest-service-role
  namespace: catest
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catest-service-rolebinding
  namespace: catest
subjects:
  - kind: ServiceAccount
    name: catest-service-account
    namespace: catest
roleRef:
  kind: Role
  name: catest-service-role
  apiGroup: rbac.authorization.k8s.io
