apiVersion: v1
kind: Service
metadata:
  name: catest-workspace
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 33082
      targetPort: 33082
      name: http
  selector:
    app: catest-workspace
---
apiVersion: v1
kind: Service
metadata:
  name: catest-intelligence
  namespace: catest
spec:
  type: LoadBalancer
  ports:
    - port: 33083
      targetPort: 33083
      name: http
  selector:
    app: catest-intelligence
