apiVersion: v1
kind: Secret
metadata:
  name: catest-app-secrets
  namespace: catest
type: Opaque
stringData:
  DATABASE_URL: "postgres://catest:password@postgres.catest.svc.cluster.local:34321/catest_gateway"
  JWT_HS256_SECRET: "x+wzSlBSRL8vcnMc5jZBzNyOaGxbVQJzzKFk7NYb/4I="
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "lidian727@gmail.com"
  SMTP_PASS: "nrldpgjblgijkmlg"
  NEXT_PUBLIC_PORT_WEB_BASE: "33000"
  NEXT_PUBLIC_PORT_WEB_WORKSPACE: "33001"
  NEXT_PUBLIC_PORT_WEB_RAG: "33002"
  NEXT_PUBLIC_PORT_WEB_REVIEW: "33003"
  QDRANT_API_KEY: "password"
